[theme]
primaryColor = "#12d6e3"
backgroundColor = "#07131f"
secondaryBackgroundColor = "#0d2538"
textColor = "#f5fbff"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[logger]
level = "error"
